baseURL = 'https://internals.tensorchord.ai/'
languageCode = 'en-us'
title = 'TensorChord Internals'
theme = 'hugo-book'

# enable 'last modified by' date and git author
enableGitInfo = true

# disable for doc
disableKinds = ['taxonomy', 'taxonomyTerm']

[menu]
[[menu.after]]
name = "GitHub"
url = "https://github.com/tensorchord"
weight = 10

[[menu.after]]
name = "Discord"
url = "https://discord.gg/KqswhpVgdU"
weight = 20

[params]
BookTheme = 'auto'
BookLogo = 'envd.svg'
BookRepo = 'https://github.com/tensorchord/tensorchord-internals'
BookCommitPath = 'commit'
BookComments = false
